WIP - Introduce modular testing
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ joda-money ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to ...\joda-money\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] ...\joda-money\src\test\java\module-info.java:[20,5]
   error: modules are not supported in -source 8
   use -source 9 or higher to enable modules