Upgrade to junit-vintage-engine 5.3.0
Also switch mode to "Mode 2 - MODULAR_CLASSIC_TEST"

3 errors pending:

[..]
  | +-- test_subtract [OK]
  | '-- test_max_differentCurrencies [OK]
  '-- TestStringConvert [OK]
    +-- test_BigMoney [X] org/joda/convert/StringConvert
    +-- test_CurrencyUnit [X] org/joda/convert/StringConvert
    '-- test_Money [X] org/joda/convert/StringConvert

Failures (3):
  JUnit Vintage:TestStringConvert:test_BigMoney
    MethodSource [className = 'org.joda.money.TestStringConvert', methodName = 'test_BigMoney', methodParameterTypes = '']
    => java.lang.NoClassDefFoundError: org/joda/convert/StringConvert
       org.joda.money/org.joda.money.TestStringConvert.test_BigMoney(TestStringConvert.java:31)
       ...